// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgruudmpjdjzetbeynzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtncnV1ZG1wamRqemV0YmV5bnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Mjg2ODYsImV4cCI6MjA2NjAwNDY4Nn0.WxW-mIbKC4sekJ92T0zxx8TshUzu3iedPKmtgnGoZeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);